package src.integration;

import src.integration.models.FamilyModel;
import src.integration.models.PersonModel;

public class Main {
    public static void main(String[] args) {
        String file = "src/integration/resources/softhouse-test.txt";
        Parser parser = new Parser();
        XMLWriter xmlWriter = new XMLWriter();

        var personList = parser.ParseFile(file);
        if(xmlWriter.PrintToXML(personList)){
            System.out.println("XML printed.");
        }
    }

    //Helper-function that prints the data generated by the parser
    public static void PrintParsedResult(String file){
        Parser parser = new Parser();
        var personList = parser.ParseFile(file);

        for (PersonModel person : personList) {
            System.out.println("---- Person ----");
            System.out.println("Name: " + person.firstName + " " + person.lastName);

            if (person.phoneNumbers.isPresent()){
                System.out.println("Phone (mobile): " + person.phoneNumbers.get().mobile);
                System.out.println("Phone (landline): " + person.phoneNumbers.get().landline);
            }

            if (person.addresses.isPresent()) {
                System.out.println("Address:");
                System.out.println("  Street: " + person.addresses.get().street);
                System.out.println("  City: " + person.addresses.get().city);
                person.addresses.get().zip.ifPresent(zip -> System.out.println("  Zip: " + zip));
            }

            for (FamilyModel family : person.familyMembers) {
                System.out.println("---- Family Member ----");
                System.out.println("Name: " + family.name);
                System.out.println("Born: " + family.birthDate);

                if (family.phoneNumbers.isPresent()) {
                    System.out.println("Family Phone (mobile): " + family.phoneNumbers.get().mobile);
                    System.out.println("Family Phone (landline): " + family.phoneNumbers.get().landline);
                }

                if (family.addresses.isPresent()) {
                    System.out.println("Family Address:");
                    System.out.println("  Street: " + family.addresses.get().street);
                    System.out.println("  City: " + family.addresses.get().city);
                    family.addresses.get().zip.ifPresent(zip -> System.out.println("  Zip: " + zip));
                }
            }

            System.out.println();
        }
    }
}
